### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by PhoenixAlx** [njvack/bioread#17]
Hi,
good job this library. Thanks

But I have a problem installing with easy_install 

```
lib/python3.5/site-packages/ez_setup.py", line 467, in _extractall
    self.chown(tarinfo, dirpath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
```

Can you help me?

**Comment by njvack** [comment]
Gak, I don't know what's up with that. Might be you're on py3.5 -- I'm mainly testing on 2.7.9 at the moment. I'm working on the library again these days, so it'll hopefully work on everything from 2.7 through 3.5 when I'm done, but that'll be a bit of time.

Redoing packaging will probably be a part of all this, too.

**Comment by PhoenixAlx** [comment]
@njvack 
I could look at the code and see if I could fix it . If I found something I tell you

**Comment by PhoenixAlx** [comment]
Ok, I have done 
git clone --recursive of https://github.com/njvack/bioread 
python setup.py install
and it works ^_^

**Comment by njvack** [comment]
Oh my goodness, my readme tells folks to use `easy_install` which is bad; `pip install bioread` will probably work.

wow bioread is ancient

I'll still look at how this gets packages as part of this release cycle.

Thanks for the bug report, and glad you're sorted.
